### PR TITLE
Avoid crash when invalid URI is passed to test file write

### LINKED ISSUE #124: [BUG] Mirth Client Crashes when doing a Test Write on File Writer with no value in Directory field
**Describe the bug**
Mirth Client Crashes when doing a Test Write on File Writer with no value in Directory field and Mirth 3.12 running inside of a container.

**To Reproduce**
Create a channel and set destination to File Writer
Click Test Write

**Expected behavior**
Not crash and given an error.

**Actual behavior**
An unexpected error occurred.  [Full message](https://github.com/user-attachments/files/20848301/writefiletest.txt)

**Related**
Originally [#4963](https://github.com/nextgenhealthcare/connect/issues/4963)
Summary #121

### PR DESCRIPTION
**Pull request by mgaffigan**
Closes #124 / original [#4963](https://github.com/nextgenhealthcare/connect/issues/4963).

Updates server to provide a normal failure when a URI can't be parsed.

Implementation notes:
- I did not add separate client-side verification since it's unclear to me how to validate in a manner that supports all of the various file write options.  The new error when no directory is specified is 
new error

### CODE REVIEW

**Review by kryskool — APPROVED** [review]

File: server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java [hunk 1]
```diff
@@ -65,7 +65,12 @@ protected ConnectionTestResponse testReadOrWrite(String channelId, String channe
             int timeout = Integer.parseInt(timeoutString);
 
             FileConnector fileConnector = new FileConnector(channelId, connectorProperties, null);
-            URI address = fileConnector.getEndpointURI(host, scheme, schemeProperties, secure);
+            URI address;
+            try {
+                address = fileConnector.getEndpointURI(host, scheme, schemeProperties, secure);
+            } catch (Exception e) {
```
Comment (jonbartels) [inline server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java:71]: Can/should specific exception types be caught or is a pokemon handler (gotta catch em all!)  OK here?

Comment (tonygermano) [reply server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java:71]: I was looking at this one last night. I think it's fine if we don't want to leak uncaught exceptions. There's only one line in the try, so we know what failed, and the exception message is included.

Comment (mgaffigan) [reply server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java:71]: We can drop down to just catching `URISyntaxException`, but I'm not sure it is any worse/better.  The catch at line 103 will swallow everything regardless.

Comment (tonygermano) [reply server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java:71]: My vote is to keep it catching all Exceptions.

**Review by kpalang — APPROVED** [review]

File: server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java (hunk 1 above)
Comment (jonbartels) [reply server/src/com/mirth/connect/connectors/file/FileConnectorServlet.java:71]: I'm OK with catching all exceptions. Ty for discussing!
